### PR TITLE
Make compatible with non-Windows platforms

### PR DESCRIPTION
**Pull request by Tatsh**
This makes the code build on macOS, Linux, etc, without losing compatibility with Windows.

### CODE REVIEW

**Comment by DarbyCrash** [comment]
I have compiled it on Debian Stretch and I have this error:

`$ ./widevine_decrypter
Syntax : ./widevine_decrypter {encrypted_file} {stream_id} {info_path} {decrypted_path}
*** Error in `./widevine_decrypter': double free or corruption (!prev): 0x00005584c176f1d0 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x70bfb)[0x7f70867abbfb]
/lib/x86_64-linux-gnu/libc.so.6(+0x76fc6)[0x7f70867b1fc6]
/lib/x86_64-linux-gnu/libc.so.6(+0x7780e)[0x7f70867b280e]
/lib/x86_64-linux-gnu/libc.so.6(__cxa_finalize+0x8f)[0x7f7086770caf]
/home/darby/Scrivania/video_decrypter/widevine_decrypter/src/build/wvdecrypter/libssd_wv.so(+0x5d6a3)[0x7f70877f56a3]
======= Memory map: ========
5584bfa99000-5584bfbb8000 r-xp 00000000 08:13 4215047                    /home/darby/Scrivania/video_decrypter/widevine_decrypter/src/build/widevine_decrypter
5584bfdb7000-5584bfdc2000 r--p 0011e000 08:13 4215047                    /home/darby/Scrivania/video_decrypter/widevine_decrypter/src/build/widevine_decrypter
5584bfdc2000-5584bfdc4000 rw-p 00129000 08:13 4215047                    /home/darby/Scrivania/video_decrypter/widevine_decrypter/src/build/widevine_decrypter
5584c175d000-5584c178f000 rw-p 00000000 00:00 0                          [heap]
7f7080000000-7f7080021000 rw-p 00000000 00:00 0 
7f7080021000-7f7084000000 ---p 00000000 00:00 0 
7f708673b000-7f70868d0000 r-xp 00000000 08:13 1580927                    /lib/x86_64-linux-gnu/libc-2.24.so
7f70868d0000-7f7086ad0000 ---p 00195000 08:13 1580927                    /lib/x86_64-linux-gnu/libc-2.24.so
7f7086ad0000-7f7086ad4000 r--p 00195000 08:13 1580927                    /lib/x86_64-linux-gnu/libc-2.24.so
7f7086ad4000-7f7086ad6000 rw-p 00199000 08:13 1580927                    /lib/x86_64-linux-gnu/libc-2.24.so
7f7086ad6000-7f7086ada000 rw-p 00000000 00:00 0 
7f7086ada000-7f7086af0000 r-xp 00000000 08:13 1572868                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7f7086af0000-7f7086cef000 ---p 00016000 08:13 1572868                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7f7086cef000-7f7086cf0000 r--p 00015000 08:13 1572868                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7f7086cf0000-7f7086cf1000 rw-p 00016000 08:13 1572868                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7f7086cf1000-7f7086df4000 r-xp 00000000 08:13 1580931                    /lib/x86_64-linux-gnu/libm-2.24.so
7f7086df4000-7f7086ff3000 ---p 00103000 08:13 1580931                    /lib/x86_64-linux-gnu/libm-2.24.so
7f7086ff3000-7f7086ff4000 r--p 00102000 08:13 1580931                    /lib/x86_64-linux-gnu/libm-2.24.so
7f7086ff4000-7f7086ff5000 rw-p 00103000 08:13 1580931                    /lib/x86_64-linux-gnu/libm-2.24.so
7f7086ff5000-7f7087167000 r-xp 00000000 08:13 791935                     /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.22
7f7087167000-7f7087367000 ---p 00172000 08:13 791935                     /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.22
7f7087367000-7f7087371000 r--p 00172000 08:13 791935                     /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.22
7f7087371000-7f7087373000 rw-p 0017c000 08:13 791935                     /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.22
7f7087373000-7f7087377000 rw-p 00000000 00:00 0 
7f7087377000-7f708738f000 r-xp 00000000 08:13 1580942                    /lib/x86_64-linux-gnu/libpthread-2.24.so
7f708738f000-7f708758e000 ---p 00018000 08:13 1580942                    /lib/x86_64-linux-gnu/libpthread-2.24.so
7f708758e000-7f708758f000 r--p 00017000 08:13 1580942                    /lib/x86_64-linux-gnu/libpthread-2.24.so
7f708758f000-7f7087590000 rw-p 00018000 08:13 1580942                    /lib/x86_64-linux-gnu/libpthread-2.24.so
7f7087590000-7f7087594000 rw-p 00000000 00:00 0 
7f7087594000-7f7087597000 r-xp 00000000 08:13 1580930                    /lib/x86_64-linux-gnu/libdl-2.24.so
7f7087597000-7f7087796000 ---p 00003000 08:13 1580930                    /lib/x86_64-linux-gnu/libdl-2.24.so
7f7087796000-7f7087797000 r--p 00002000 08:13 1580930                    /lib/x86_64-linux-gnu/libdl-2.24.so
7f7087797000-7f7087798000 rw-p 00003000 08:13 1580930                    /lib/x86_64-linux-gnu/libdl-2.24.so
7f7087798000-7f708786b000 r-xp 00000000 08:13 4215019                    /home/darby/Scrivania/video_decrypter/widevine_decrypter/src/build/wvdecrypter/libssd_wv.so
7f708786b000-7f7087a6a000 ---p 000d3000 08:13 4215019                    /home/darby/Scrivania/video_decrypter/widevine_decrypter/src/build/wvdecrypter/libssd_wv.so
7f7087a6a000-7f7087a74000 r--p 000d2000 08:13 4215019                    /home/darby/Scrivania/video_decrypter/widevine_decrypter/src/build/wvdecrypter/libssd_wv.so
7f7087a74000-7f7087a76000 rw-p 000dc000 08:13 4215019                    /home/darby/Scrivania/video_decrypter/widevine_decrypter/src/build/wvdecrypter/libssd_wv.so
7f7087a76000-7f7087a99000 r-xp 00000000 08:13 1580633                    /lib/x86_64-linux-gnu/ld-2.24.so
7f7087c72000-7f7087c77000 rw-p 00000000 00:00 0 
7f7087c96000-7f7087c99000 rw-p 00000000 00:00 0 
7f7087c99000-7f7087c9a000 r--p 00023000 08:13 1580633                    /lib/x86_64-linux-gnu/ld-2.24.so
7f7087c9a000-7f7087c9b000 rw-p 00024000 08:13 1580633                    /lib/x86_64-linux-gnu/ld-2.24.so
7f7087c9b000-7f7087c9c000 rw-p 00000000 00:00 0 
7ffc17e46000-7ffc17e67000 rw-p 00000000 00:00 0                          [stack]
7ffc17eac000-7ffc17eaf000 r--p 00000000 00:00 0                          [vvar]
7ffc17eaf000-7ffc17eb1000 r-xp 00000000 00:00 0                          [vdso]
Annullato
`

**Comment by Tatsh** [comment]
You should build with debug symbols and show that backtrack.

**Comment by DarbyCrash** [comment]
How can I compile in the right way?
From build folder "cmake .. && make" is right?

**Comment by Tatsh** [comment]
Use `cmake -DCMAKE_BUILD_TYPE=Debug ..`

**Comment by DarbyCrash** [comment]
`$ ./widevine_decrypter
Syntax : ./widevine_decrypter {encrypted_file} {stream_id} {info_path} {decrypted_path}
*** Error in `./widevine_decrypter': double free or corruption (!prev): 0x000055992d5651d0 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x70bfb)[0x7fd9a61dabfb]
/lib/x86_64-linux-gnu/libc.so.6(+0x76fc6)[0x7fd9a61e0fc6]
/lib/x86_64-linux-gnu/libc.so.6(+0x7780e)[0x7fd9a61e180e]
./widevine_decrypter(_ZN9AP4_ArrayIN12AP4_MetaData7KeyInfoEED1Ev+0x3a)[0x55992bedc63a]
/lib/x86_64-linux-gnu/libc.so.6(__cxa_finalize+0x8f)[0x7fd9a619fcaf]
/home/darby/Scrivania/video_decrypter/widevine_decrypter/src/build/wvdecrypter/libssd_wv.so(+0x94493)[0x7fd9a725b493]
======= Memory map: ========
55992bdb4000-55992bf63000 r-xp 00000000 08:13 4215252                    /home/darby/Scrivania/video_decrypter/widevine_decrypter/src/build/widevine_decrypter
55992c163000-55992c16e000 r--p 001af000 08:13 4215252                    /home/darby/Scrivania/video_decrypter/widevine_decrypter/src/build/widevine_decrypter
55992c16e000-55992c170000 rw-p 001ba000 08:13 4215252                    /home/darby/Scrivania/video_decrypter/widevine_decrypter/src/build/widevine_decrypter
55992d553000-55992d585000 rw-p 00000000 00:00 0                          [heap]
7fd9a0000000-7fd9a0021000 rw-p 00000000 00:00 0 
7fd9a0021000-7fd9a4000000 ---p 00000000 00:00 0 
7fd9a616a000-7fd9a62ff000 r-xp 00000000 08:13 1580927                    /lib/x86_64-linux-gnu/libc-2.24.so
7fd9a62ff000-7fd9a64ff000 ---p 00195000 08:13 1580927                    /lib/x86_64-linux-gnu/libc-2.24.so
7fd9a64ff000-7fd9a6503000 r--p 00195000 08:13 1580927                    /lib/x86_64-linux-gnu/libc-2.24.so
7fd9a6503000-7fd9a6505000 rw-p 00199000 08:13 1580927                    /lib/x86_64-linux-gnu/libc-2.24.so
7fd9a6505000-7fd9a6509000 rw-p 00000000 00:00 0 
7fd9a6509000-7fd9a651f000 r-xp 00000000 08:13 1572868                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7fd9a651f000-7fd9a671e000 ---p 00016000 08:13 1572868                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7fd9a671e000-7fd9a671f000 r--p 00015000 08:13 1572868                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7fd9a671f000-7fd9a6720000 rw-p 00016000 08:13 1572868                    /lib/x86_64-linux-gnu/libgcc_s.so.1
7fd9a6720000-7fd9a6823000 r-xp 00000000 08:13 1580931                    /lib/x86_64-linux-gnu/libm-2.24.so
7fd9a6823000-7fd9a6a22000 ---p 00103000 08:13 1580931                    /lib/x86_64-linux-gnu/libm-2.24.so
7fd9a6a22000-7fd9a6a23000 r--p 00102000 08:13 1580931                    /lib/x86_64-linux-gnu/libm-2.24.so
7fd9a6a23000-7fd9a6a24000 rw-p 00103000 08:13 1580931                    /lib/x86_64-linux-gnu/libm-2.24.so
7fd9a6a24000-7fd9a6b96000 r-xp 00000000 08:13 791935                     /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.22
7fd9a6b96000-7fd9a6d96000 ---p 00172000 08:13 791935                     /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.22
7fd9a6d96000-7fd9a6da0000 r--p 00172000 08:13 791935                     /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.22
7fd9a6da0000-7fd9a6da2000 rw-p 0017c000 08:13 791935                     /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.22
7fd9a6da2000-7fd9a6da6000 rw-p 00000000 00:00 0 
7fd9a6da6000-7fd9a6dbe000 r-xp 00000000 08:13 1580942                    /lib/x86_64-linux-gnu/libpthread-2.24.so
7fd9a6dbe000-7fd9a6fbd000 ---p 00018000 08:13 1580942                    /lib/x86_64-linux-gnu/libpthread-2.24.so
7fd9a6fbd000-7fd9a6fbe000 r--p 00017000 08:13 1580942                    /lib/x86_64-linux-gnu/libpthread-2.24.so
7fd9a6fbe000-7fd9a6fbf000 rw-p 00018000 08:13 1580942                    /lib/x86_64-linux-gnu/libpthread-2.24.so
7fd9a6fbf000-7fd9a6fc3000 rw-p 00000000 00:00 0 
7fd9a6fc3000-7fd9a6fc6000 r-xp 00000000 08:13 1580930                    /lib/x86_64-linux-gnu/libdl-2.24.so
7fd9a6fc6000-7fd9a71c5000 ---p 00003000 08:13 1580930                    /lib/x86_64-linux-gnu/libdl-2.24.so
7fd9a71c5000-7fd9a71c6000 r--p 00002000 08:13 1580930                    /lib/x86_64-linux-gnu/libdl-2.24.so
7fd9a71c6000-7fd9a71c7000 rw-p 00003000 08:13 1580930                    /lib/x86_64-linux-gnu/libdl-2.24.so
7fd9a71c7000-7fd9a730f000 r-xp 00000000 08:13 4215233                    /home/darby/Scrivania/video_decrypter/widevine_decrypter/src/build/wvdecrypter/libssd_wv.so
7fd9a730f000-7fd9a750f000 ---p 00148000 08:13 4215233                    /home/darby/Scrivania/video_decrypter/widevine_decrypter/src/build/wvdecrypter/libssd_wv.so
7fd9a750f000-7fd9a7519000 r--p 00148000 08:13 4215233                    /home/darby/Scrivania/video_decrypter/widevine_decrypter/src/build/wvdecrypter/libssd_wv.so
7fd9a7519000-7fd9a751e000 rw-p 00152000 08:13 4215233                    /home/darby/Scrivania/video_decrypter/widevine_decrypter/src/build/wvdecrypter/libssd_wv.so
7fd9a751e000-7fd9a7541000 r-xp 00000000 08:13 1580633                    /lib/x86_64-linux-gnu/ld-2.24.so
7fd9a771a000-7fd9a771f000 rw-p 00000000 00:00 0 
7fd9a773e000-7fd9a7741000 rw-p 00000000 00:00 0 
7fd9a7741000-7fd9a7742000 r--p 00023000 08:13 1580633                    /lib/x86_64-linux-gnu/ld-2.24.so
7fd9a7742000-7fd9a7743000 rw-p 00024000 08:13 1580633                    /lib/x86_64-linux-gnu/ld-2.24.so
7fd9a7743000-7fd9a7744000 rw-p 00000000 00:00 0 
7fff85919000-7fff8593a000 rw-p 00000000 00:00 0                          [stack]
7fff8595e000-7fff85961000 r--p 00000000 00:00 0                          [vvar]
7fff85961000-7fff85963000 r-xp 00000000 00:00 0                          [vdso]
Annullato
`

**Comment by DarbyCrash** [comment]
I have the same output also with DEBUG release.

**Comment by Tatsh** [comment]
Temporary fix: edit `widevine_decrypter/lib/libbento4/Core/Ap4Array.h` and delete line 118. This may cause leaks.

```patch
diff --git a/widevine_decrypter/lib/libbento4/Core/Ap4Array.h b/widevine_decrypter/lib/libbento4/Core/Ap4Array.h
index 65131a5..181366e 100644
--- a/widevine_decrypter/lib/libbento4/Core/Ap4Array.h
+++ b/widevine_decrypter/lib/libbento4/Core/Ap4Array.h
@@ -115,7 +115,6 @@ template <typename T>
 AP4_Array<T>::~AP4_Array()
 {
     Clear();
-    ::operator delete((void*)m_Items);
 }

 /*---------------------------------------------------------------------
```

You should file an issue with this project about this. This PR is not related.

**Comment by DarbyCrash** [comment]
I have build it like DEBUG and without line 118 I haven't other issues. You can delete my posts. If I have other issue I open a issue.

**Comment by DarbyCrash** [comment]
Please, I have a request very important. Is possible a static build? Sorry if I have wrote here but I can't contact you in other way.

**Comment by Tatsh** [comment]
You have to edit `lib/wvdecrypter/CMakeLists.txt`.

```patch
diff --git a/widevine_decrypter/lib/wvdecrypter/CMakeLists.txt b/widevine_decrypter/lib/wvdecrypter/CMakeLists.txt
index 73c9067..853cead 100644
--- a/widevine_decrypter/lib/wvdecrypter/CMakeLists.txt
+++ b/widevine_decrypter/lib/wvdecrypter/CMakeLists.txt
@@ -46,7 +46,7 @@ else()
     add_definitions("-DWIDEVINECDMFILENAME=\"libwidevinecdm.so\"")
   endif()

-  add_library ( ssd_wv SHARED
+  add_library ( ssd_wv STATIC
         wvdecrypter.cpp
         jsmn.c
         ../inputstream.adaptive/helpers.cpp
```

**Comment by DarbyCrash** [comment]
Thank you very much. One information, removing line 118 work only building like DEBUG.
If you build it like RELEASE do you have seg fault.

**Comment by dcxmurph** [comment]
Hey, I'm trying to use the program. What is the "stream ID" and "info path?" Can you help me with how I'm supposed to use this program and exactly what it does?

**Comment by dcxmurph** [comment]
I think I found what stream ID meant. I tried a video, but got:

dlopen(/Users/declan/video_decrypter/widevine_decrypter/src/wvdecrypter/libssd_wv.dll, 1): image not found

Anyone know what's going on?

**Comment by NaufalAriqS21** [comment]
> Hey, I'm trying to use the program. What is the "stream ID" and "info path?" Can you help me with how I'm supposed to use this program and exactly what it does?

What is stream ID & info path? The wiki is dead.

**Pull request merged**
